name: Jest Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Spin up react server for testing
        run: npm run startReact

      - name: Run tests
        run: npm test

      - name: Stop React
        run: SIGINT
